<?php

namespace App\Models;

use Carbon\Carbon;

class PurchaseReturn extends Model
{
    protected $table = 'purchase_returns';

    protected $fillable = [
        'remark','status'
    ];

    //设置类型
    protected $casts = [
        'status' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // 监听模型创建事件，在写入数据库之前触发
        static::creating(function($model) {
            // 如果模型的 no 字段为空
            if (!$model->purchase_return_no) {
                // 调用 findAvailableNo 生成订单流水号
                $model->purchase_return_no = static::findAvailableNo();
                // 如果生成失败，则终止创建订单
                if (!$model->purchase_return_no) {
                    return false;
                }
            }
            // 如果模型的 creator 字段为空
            if (!$model->creator) {

                $model->creator = 'admin';
                // 如果生成失败，则终止创建订单
                if (!$model->creator) {
                    return false;
                }
            }
        });
    }

    public static function findAvailableNo()
    {
        // 订单流水号前缀
        $prefix = 'RG';

        for ($i = 0; $i < 10; $i++) {
            // 随机生成 6 位的数字
            $no = $prefix . date('YmdHis') . str_pad(mt_rand(1, 99999), 5, 0, STR_PAD_LEFT);
            // 判断是否已经存在
            if (!static::query()->where('purchase_return_no', $no)->exists()) {
                return $no;
            }
        }

        return false;
    }

    /**
     * 提交
     */
    public function input()
    {
        $this->is_submit = 1;
        $this->submitter = 'admin';
        $this->submit_at = Carbon::now();
        $this->save();
    }

//    /**
//     * 退审
//     */
//    public function auditFaild()
//    {
//        $this->is_submit = 0;
//        $this->submitter = '';
//        $this->submit_at = null;
//        $this->save();
//    }

    /**
     * 审核
     */
    public function audit()
    {
        $this->audit_at = Carbon::now();
        $this->auditor = 'admin';
        $this->is_audit = 1;
        $this->save();
    }


    /**
     * 打印
     */
    public function print()
    {
        $this->is_print = 1;
        $this->save();
    }



    public function purchaseReturnDetails()
    {
        return $this->hasMany(PurchaseReturnDetail::class,'purchase_returns_id');
    }



}
